# Use root/example as user/password credentials
version: '3.1'

services:
    web:
        image: nginx:1.19.2-alpine
        volumes:
        - ./templates:/etc/nginx/templates
        ports:
        - "8082:80"
        environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80
    app:
        image: php:7.4-fpm-alpine

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:80